name: Build and Push Multi-Arch Image with CVE Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      # Cache na DockerHubie: mekkr/app-cache
      DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/app-cache
      # Finalny obraz w GHCR: ghcr.io/M1K0L4AJ/weather-app
      IMAGE_NAME: ghcr.io/${{ secrets.GHCR_USERNAME }}/weather-app

    steps:
      # 1) Set up QEMU (aby móc tworzyć obrazy multi-arch)
      - name: Set up QEMU (to support building multi-arch images)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --allow-insecure-entitlement security.insecure

      # 2) Logowanie do DockerHuba (żeby użyć cache) i do GHCR (by wypchnąć obraz)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.CR_PAT }}

      # 3) Budowa multi-arch obrazu i zapis cache w DockerHubie
      - name: Build and push multi-arch image
        uses: docker/build-push-action@v4
        with:
          # kontekst = katalog główny repo (jeden poziom wyżej niż .github/workflows)
          context: ../
          file: ../Dockerfile
          platforms: linux/amd64,linux/arm64

          # Pobierz cache z DockerHuba: mekkr/app-cache:cache-latest
          cache-from: type=registry,ref=${{ env.DOCKERHUB_REPO }}:cache-latest
          # Zapisz nowy cache pod tagiem: mekkr/app-cache:cache-<SHA>
          cache-to:   type=registry,ref=${{ env.DOCKERHUB_REPO }}:cache-${{ github.sha }},mode=max

          # Tagi, które przygotujemy (ale jeszcze nie wypychamy):
          #  - latest
          #  - <SHA>
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          push: false

      # 4) Instalacja Trivy (narzędzie do skanowania CVE)
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      # 5) Skanowanie obrazu Trivy – wyszukujemy CVE o poziomie CRITICAL i HIGH
      - name: Run Trivy scan on built images
        id: trivy-scan
        run: |
          trivy image --exit-code 1 --severity CRITICAL,HIGH ${{ env.IMAGE_NAME }}:latest --platform linux/amd64
          trivy image --exit-code 1 --severity CRITICAL,HIGH ${{ env.IMAGE_NAME }}:latest --platform linux/arm64

      # 6) Jeśli Trivy nie wykrył CRITICAL/HIGH CVE, wypychamy obrazy do GHCR
      - name: Push images to GHCR
        if: ${{ success() }}
        run: |
          docker push ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}

